version: '2'

services:
  master:
    build: ./hadoop-master
    ports:
      - "9870:9870"
      - "8088:8088"
      - "19888:19888"
      - "8188:8188"
      - "50070:50070"
    volumes:
      - ./project-data/:/project-data
    container_name: "master"
